# phrases to be used for the game


PHRASE_LIST = [
  'BETTER LATE THAN NEVER',
  'HANG IN THERE',
  'HELLO WORLD',
  'A DIAMOND IN THE ROUGH',
  'BEST OF BOTH WORLDS',
  'PIECE OF CAKE',
  'YOUR GUESS IS AS GOOD AS MINE',
  'SO FAR SO GOOD',
  'HANG IN THERE',
]
